service: interrogator

provider:
  name: aws
  profile: jdl
  region: us-east-1
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}

package:
  exclude:
    - test/**

functions:
  slackEvent:
    handler: slackHandler.handleEvent
    name: ${self:provider.stage}-slackEvent
    events:
      - http:
          path: events
          method: post
